/*
 * Dcm_Service_DiagnosticSessionControl.h
 *
 *  Created on: Oct 24, 2023
 *      Author: FER3CLJ
 */

#ifndef INC_DCM_SERVICE_DIAGNOSTICSESSIONCONTROL_H_
#define INC_DCM_SERVICE_DIAGNOSTICSESSIONCONTROL_H_

#include <stdint.h>

#define uint8_t char

//Sessions
#define DCM_SESSION_DEFAULT_SESSION 0X01
#define DCM_SESSION_PROGRAMMING_SESSION 0X02
#define DCM_SESSION_EXTENDED_DIAGNOSTIC_SESSION 0X03
#define DCM_SESSION_SAFETY_SYSTEM_DIAGNOSTIC_SESSION 0X04

//NRC
//#define DCM_NRC_INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT 0X13
//#define DCM_NRC_SUBFUNCTION_NOT_SUPPORTED 0X12
#define DCM_NRC_SUBFUNCTION_NOT_SUPPORTED_IN_ACTIVE_DIAGNOSTIC_SESSION 0X7E

//Time parameters
#define TIMING_FOR_ACTIVATED_SESSION_P2_SERVER_MAX_HB 0x00
#define TIMING_FOR_ACTIVATED_SESSION_P2_SERVER_MAX_LB 0x32
#define TIMING_FOR_ACTIVATED_SESSION_P2_SERVER_MAX_STAR_HB 0x01
#define TIMING_FOR_ACTIVATED_SESSION_P2_SERVER_MAX_STAR_LB 0xF4

uint8_t Dcm_Service_DiagnosticSessionControl(uint8_t *requestMessageData, uint8_t requestMessageLength, uint8_t *responseData, uint8_t *responseDataLength);

#endif /* INC_DCM_SERVICE_DIAGNOSTICSESSIONCONTROL_H_ */
